server:
  port: 8000
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: aaa

person:
  name: xixi
  age: 19
  birth-day: 2021/10/12 12:12:12
  like: true
  child:
    name: oo
    age: 20
    birthday: 2018/10/21
    text: ["abc", "def"]
  dogs:
    - id: 5
      name: gg1
    - id: 6
      name: gg2
  cats:
    c1:
      name: mm1
      id: 5
    c2: {name: mm2, id: 3 }